export default function Guarantee() {
  return (
    <section className="py-24 px-4 bg-[#f8fafc]">
      <div className="max-w-4xl mx-auto">
        <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="bg-[#1D4ED8] px-8 py-6 flex items-center gap-4">
            <div className="w-14 h-14 bg-white/20 rounded-2xl flex items-center justify-center shrink-0">
              <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
                <path d="M9 12l2 2 4-4" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </div>
            <div>
              <h2 className="text-2xl font-bold text-white" style={{ fontFamily: 'var(--font-display)' }}>
                12-Month Satisfaction Guarantee
              </h2>
              <p className="text-blue-200 text-sm mt-0.5">Industry-unique performance commitment</p>
            </div>
          </div>

          <div className="px-8 py-8">
            <p className="text-slate-600 leading-relaxed text-base mb-6">
              We reasonably expect OmniFunds to beat the returns generated by the S&P 500 index by at
              least <strong className="text-slate-900">20%</strong> over the year following your purchase.
              If OmniFunds does not achieve this performance as defined below, the License Fee shall be refunded.
            </p>

            <div className="grid sm:grid-cols-3 gap-4 mb-8">
              {[
                { icon: '📈', title: 'Beat S&P by 20%+', desc: 'Clear, measurable target' },
                { icon: '💰', title: 'Full fee refund', desc: 'If target is not met' },
                { icon: '📋', title: 'Defined terms', desc: 'Transparent methodology' },
              ].map((item) => (
                <div key={item.title} className="bg-[#f8fafc] rounded-xl p-4 text-center border border-slate-100">
                  <p className="text-2xl mb-2">{item.icon}</p>
                  <p className="font-semibold text-slate-900 text-sm mb-1">{item.title}</p>
                  <p className="text-xs text-slate-500">{item.desc}</p>
                </div>
              ))}
            </div>

            <a href="#demo"
              className="inline-flex items-center gap-2 bg-[#1D4ED8] hover:bg-[#1e40af] text-white font-semibold px-8 py-4 rounded-full text-base transition-colors shadow-lg shadow-blue-500/20">
              Book a Free Demo
              <svg width="16" height="16" viewBox="0 0 20 20" fill="currentColor">
                <path fillRule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clipRule="evenodd" />
              </svg>
            </a>
          </div>
        </div>
      </div>
    </section>
  )
}
